import { PrismaClient } from "@prisma/client";

export default async function seedEspecificacionesAdicionales(prisma: PrismaClient) {

       await prisma.especificacionesAdicionales.createMany({
    data: [
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "4 DDR3 1333 MHZ", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "AMD PHENOM II" },
    { memoriaRam: "8", modulosRam: "2", capacidadDisco: "320", tipoDisco: "HDD", procesador: "AMD PHENOM II" },
    { memoriaRam: "8 DDR3 1333MHZ", modulosRam: "2", capacidadDisco: "500", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "512 MB DDR2 533MHZ", modulosRam: "1", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "1,25 DDR 400", modulosRam: "2", capacidadDisco: "40", tipoDisco: "HDD", procesador: "PENTIUM 4" },
    { memoriaRam: "NO POSEE", modulosRam: "N/A", capacidadDisco: "320", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "2 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "NO POSEE", modulosRam: "N/A", capacidadDisco: "NO POSEE", tipoDisco: "N/A", procesador: "AMD X2" },
    { memoriaRam: "512MB", modulosRam: "1", capacidadDisco: "NO POSEE", tipoDisco: "N/A", procesador: "PENTIUM DUAL CORE" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "1DDR2 667MHZ", modulosRam: "1", capacidadDisco: "160", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "80", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "0,5", modulosRam: "1", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3 (10700)", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "PENTIUM DUAL CORE" },
    { memoriaRam: "4 (10700)", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "512 PC2 (5300)", modulosRam: "1", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "512 MB PC2 (5300)", modulosRam: "1", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "2 PC2 (5300)", modulosRam: "4", capacidadDisco: "150", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "4 DDR3 (10700)", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "16 DDR4 (3200)", modulosRam: "1", capacidadDisco: "512", tipoDisco: "M2", procesador: "i5" },
    { memoriaRam: "8 PC3 (12800)", modulosRam: "2", capacidadDisco: "120", tipoDisco: "SDD", procesador: "i7" },
    { memoriaRam: "2 DDR3 (10700)", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "CORE 2DUO" },
    { memoriaRam: "512", modulosRam: "1", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "2 PC3 (10700)", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "16 DDR4 (1600)", modulosRam: "1", capacidadDisco: "512", tipoDisco: "M2", procesador: "i5" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "8 DDR4 (2400)", modulosRam: "1", capacidadDisco: "120", tipoDisco: "SSD", procesador: "i5" },
    { memoriaRam: "500", modulosRam: "2", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM 4" },
    { memoriaRam: "128MG", modulosRam: "1", capacidadDisco: "N/A", tipoDisco: "N/A", procesador: "PENTIUM 4" },
    { memoriaRam: "16 DDR4 (3200)", modulosRam: "1", capacidadDisco: "500", tipoDisco: "M2", procesador: "i5" },
    { memoriaRam: "2 PC2 (6400)", modulosRam: "2", capacidadDisco: "320", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "I5" },
    { memoriaRam: "16 DDR4 (3200)", modulosRam: "1", capacidadDisco: "512", tipoDisco: "M2", procesador: "I5" },
    { memoriaRam: "4 PC3 10700", modulosRam: "1", capacidadDisco: "120", tipoDisco: "SSD", procesador: "AMD" },
    { memoriaRam: "6 PC3 10700", modulosRam: "2", capacidadDisco: "320", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 PC3 12800", modulosRam: "1", capacidadDisco: "1000", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "2 PC3 10600", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "CORE2 DUO" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "250", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "16 DDR4 2666MHZ", modulosRam: "2", capacidadDisco: "250", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "8 DDR3 1600 MHZ", modulosRam: "2", capacidadDisco: "500", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "4 DDR2 667 MHZ", modulosRam: "4", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "512MB DDR 400 MHZ", modulosRam: "1", capacidadDisco: "40", tipoDisco: "HDD", procesador: "PENTIUM 4" },
    { memoriaRam: "2 DDR2 667MHZ", modulosRam: "1", capacidadDisco: "250", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2DDR2 667MHZ", modulosRam: "1", capacidadDisco: "250", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "512", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "1.5 DDR2 667MHZ", modulosRam: "2", capacidadDisco: "160", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "8 DDR3", modulosRam: "2", capacidadDisco: "1000", tipoDisco: "HDD", procesador: "CORE I7" },
    { memoriaRam: "4 DDR3 1333 MHZ", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "AMD PHENOM" },
    { memoriaRam: "4 DDR3 1333 MHZ", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "1 DDR2 667MHZ", modulosRam: "1", capacidadDisco: "160", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "8 DDR3 1333MHZ", modulosRam: "2", capacidadDisco: "1000", tipoDisco: "HDD", procesador: "CORE I7" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "1 DDR2 667MHZ", modulosRam: "1", capacidadDisco: "NO POSEE", tipoDisco: "N/A", procesador: "CORE 2 DUO" },
    { memoriaRam: "1 DDR2 667MHZ", modulosRam: "2", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "1 DDR2 667MHZ", modulosRam: "2", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "2 PC3 10700", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 DDR3 10700", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "16 DRR4 3200", modulosRam: "1", capacidadDisco: "500", tipoDisco: "M2", procesador: "CORE I5 12GEN" },
    { memoriaRam: "8 DRR3 10700", modulosRam: "2", capacidadDisco: "1000", tipoDisco: "HDD", procesador: "CORE I7" },
    { memoriaRam: "4 DRR3 10700", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "4 DDR3 10700", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "4 DRR3 10700", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "1 DDR2 600", modulosRam: "1", capacidadDisco: "160", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 PC3(10700)", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "4 PC3(10700)", modulosRam: "1", capacidadDisco: "500", tipoDisco: "HDD", procesador: "I5" },
    { memoriaRam: "1 DR2 (667)", modulosRam: "1", capacidadDisco: "160", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "1 DDR2", modulosRam: "1", capacidadDisco: "160", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "1 DDR2", modulosRam: "2", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "1 DDR2", modulosRam: "2", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM 4" },
    { memoriaRam: "NO POSEE", modulosRam: "NO POSEE", capacidadDisco: "160", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "512 DDR2", modulosRam: "1", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM 4" },
    { memoriaRam: "512 DDR2", modulosRam: "1", capacidadDisco: "160", tipoDisco: "HDD", procesador: "PENTIUM 4" },
    { memoriaRam: "1", modulosRam: "1", capacidadDisco: "160", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "1", modulosRam: "1", capacidadDisco: "280", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2", modulosRam: "1", capacidadDisco: "160", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2", modulosRam: "1", capacidadDisco: "NO POSEE", tipoDisco: "NO POSEE", procesador: "CORE 2 DUO" },
    { memoriaRam: "2,6", modulosRam: "1", capacidadDisco: "320", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "2", modulosRam: "1", capacidadDisco: "80", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "2 DDR2 667MHZ", modulosRam: "4", capacidadDisco: "120 (4.54) GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "512 (101) GB", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (4) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "8 DDR3 1600MHZ", modulosRam: "2", capacidadDisco: "1000 (45) GB", tipoDisco: "HDD", procesador: "CORE i7" },
    { memoriaRam: "3 DDR2 400MHZ", modulosRam: "3", capacidadDisco: "100 (5) GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "4 DDR3 10700MHz", modulosRam: "1", capacidadDisco: "320 (28,4) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3 10700MHz", modulosRam: "1", capacidadDisco: "320 (12,7GB) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "16 DDR4 (1600MHz)", modulosRam: "1", capacidadDisco: "512 (94GB) GB", tipoDisco: "M2", procesador: "i5" },
    { memoriaRam: "4 PC3 10700", modulosRam: "1 SKHYNIX", capacidadDisco: "320(27) 120(8) GB", tipoDisco: "HDD Y SSD", procesador: "AMD" },
    { memoriaRam: "4 PC3 12800", modulosRam: "1 RAMAXEL", capacidadDisco: "320 (2,4) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 12800", modulosRam: "1 RAMAXEL", capacidadDisco: "1000 (83,1) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "160 (14,2) GB", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "16 DDR4 (3200)", modulosRam: "1", capacidadDisco: "512 (61GB) GB", tipoDisco: "M2", procesador: "i5" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "500 (9,99GB) GB", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1 SKHYNIX", capacidadDisco: "320 (1,1) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "500 (21GB) GB", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (17) GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "8 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "120 (4) GB", tipoDisco: "SSD", procesador: "CORE i5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (32) GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (19) GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "512 (57) GB", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "1 DDR2 533MHZ", modulosRam: "2", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "512 (29) GB", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "4 DDR3 10700MHz", modulosRam: "1", capacidadDisco: "320 (1,20GB) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3 10700MHz", modulosRam: "1", capacidadDisco: "320 (1GB) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3L 12800MHz", modulosRam: "1", capacidadDisco: "1000 (11.1GB) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 DDR3 10700MHz", modulosRam: "1", capacidadDisco: "320 (1,44) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "1 DDR2 667 MHZ", modulosRam: "1", capacidadDisco: "160 (38) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "1 DDR2 667 MHZ", modulosRam: "1", capacidadDisco: "160 (50) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "8 DDR3 1600MHZ", modulosRam: "2", capacidadDisco: "1000 (217) GB", tipoDisco: "HDD", procesador: "CORE i7" },
    { memoriaRam: "8 DDR3 1600MHZ", modulosRam: "2", capacidadDisco: "320 (136) GB", tipoDisco: "HDD", procesador: "CORE i7" },
    { memoriaRam: "4 DDR3 10700MHZ", modulosRam: "1", capacidadDisco: "120 (4GB) GB", tipoDisco: "SSD", procesador: "I5" },
    { memoriaRam: "4 DDR3 10700MHZ", modulosRam: "1", capacidadDisco: "320 (97GB) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3 10700MHZ", modulosRam: "1", capacidadDisco: "320 (36GB) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3 10700MHZ", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "512 (34GB) GB", tipoDisco: "M2", procesador: "I5" },
    { memoriaRam: "8 DDR3 12800MHZ", modulosRam: "2", capacidadDisco: "1000 (13GB) GB", tipoDisco: "HDD", procesador: "I7" },
    { memoriaRam: "4 DDR3 10600MHZ", modulosRam: "1", capacidadDisco: "500 (30GB) GB", tipoDisco: "HDD", procesador: "I5" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "512 (28GB) GB", tipoDisco: "M2", procesador: "I5" },
    { memoriaRam: "4 DRR3 10600MHZ", modulosRam: "1", capacidadDisco: "320 (44GB) GB", tipoDisco: "HDD", procesador: "I5" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "512 (19GB) GB", tipoDisco: "M2", procesador: "I5" },
    { memoriaRam: "NO POSEE", modulosRam: "NO POSEE", capacidadDisco: "NO POSEE", tipoDisco: "NO POSEE", procesador: "I5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (35.3) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "512 (308) GB", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (12.5) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "N/A", modulosRam: "N/A", capacidadDisco: "N/A", tipoDisco: "N/A", procesador: "N/A" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (36.6) GB", tipoDisco: "M2", procesador: "AMD X2" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (26.5) GB", tipoDisco: "N/A", procesador: "N/A" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (5.54) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (142) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "512 (178) GB", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "512 (117) GB", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (18.1) GB", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (1.21) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (156MB) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "2 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (11.1) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (22.9) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (5.14) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "8 DDR3 1333MHZ", modulosRam: "2", capacidadDisco: "500 (12.6) GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "1 DDR2 667 MHZ", modulosRam: "1", capacidadDisco: "160 (2.63) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "I7" },
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "I7" },
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "120/320 GB", tipoDisco: "SSD/HDD", procesador: "I7" },
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "I7" },
    { memoriaRam: "8", modulosRam: "2", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "I7" },
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "120 GB", tipoDisco: "SSD", procesador: "AMD" },
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "320/230 GB", tipoDisco: "HDD/HDD", procesador: "AMD" },
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "I3" },
    { memoriaRam: "16 DR4 (3200)", modulosRam: "1", capacidadDisco: "500 (11) GB", tipoDisco: "M2", procesador: "i5" },
    { memoriaRam: "32 PC4 (4400)", modulosRam: "1", capacidadDisco: "500 (12,8) GB", tipoDisco: "M2", procesador: "i5" },
    { memoriaRam: "32 PC4 (4400)", modulosRam: "1", capacidadDisco: "500 (29) GB", tipoDisco: "M2", procesador: "i5" },
    { memoriaRam: "16 DR4 (3200)", modulosRam: "1", capacidadDisco: "500 (32,1) GB", tipoDisco: "M2", procesador: "i5" },
    { memoriaRam: "8 DDR3 1600MHZ", modulosRam: "2", capacidadDisco: "1000 (50) GB", tipoDisco: "HDD", procesador: "CORE i7" },
    { memoriaRam: "2", modulosRam: "1", capacidadDisco: "160 (25.4) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "134 (68) GB", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "512MB DDR 400", modulosRam: "1", capacidadDisco: "40 GB", tipoDisco: "HDD", procesador: "N/A" },
    { memoriaRam: "512MB DDR2 533MHZ", modulosRam: "1", capacidadDisco: "40 (24.5) GB", tipoDisco: "HDD", procesador: "PENITUM 4" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "2", capacidadDisco: "1250 (83) GB", tipoDisco: "SSD Y HDD", procesador: "CORE i3" },
    { memoriaRam: "0,5", modulosRam: "1", capacidadDisco: "40 GB", tipoDisco: "HDD", procesador: "PENTIUM 4" },
    { memoriaRam: "2 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (38.3) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (16) GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "8 DDR3 1600MHZ", modulosRam: "2", capacidadDisco: "320 (20) GB", tipoDisco: "HDD", procesador: "CORE i7" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (21.4) GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "8 DDR3 1600MHZ", modulosRam: "2", capacidadDisco: "500 (141) GB", tipoDisco: "HDD", procesador: "CORE i7" },
    { memoriaRam: "4 DDR3 1600MHZ", modulosRam: "1", capacidadDisco: "120 (7.85) GB", tipoDisco: "SSD", procesador: "CORE i7" },
    { memoriaRam: "NO POSEE", modulosRam: "N/A", capacidadDisco: "NO POSEE", tipoDisco: "N/A", procesador: "PENTIUM" },
    { memoriaRam: "512", modulosRam: "1", capacidadDisco: "40 GB", tipoDisco: "HDD", procesador: "PENTIUM 4" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (2.0) GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (9) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "2 PC3 (10700)", modulosRam: "1", capacidadDisco: "120 (3) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2 PC3 (10700)", modulosRam: "1", capacidadDisco: "120 (2,9) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "500 (240) GB", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "8 PC3 (10700)", modulosRam: "2", capacidadDisco: "320 (2) GB", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "1 DDR2 (6400)", modulosRam: "1", capacidadDisco: "80 (5) GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "500 (80) GB", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "8 PC3 (12800)", modulosRam: "2", capacidadDisco: "1000 (336) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "32 DDR4 (3200)", modulosRam: "4", capacidadDisco: "1000 (61) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "512 DDR2 (6400)", modulosRam: "1", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "513 DDR2 (6400)", modulosRam: "1", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "514 DDR2 (6400)", modulosRam: "1", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "515 DDR2 (6400)", modulosRam: "1", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "516 DDR2 (6400)", modulosRam: "1", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "N/A", modulosRam: "N/A", capacidadDisco: "N/A", tipoDisco: "N/A", procesador: "N/A" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "I7" },
    { memoriaRam: "2 GB", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "4 GB", modulosRam: "2", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "I5" },
    { memoriaRam: "1 GB", modulosRam: "1", capacidadDisco: "160 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "8 GB", modulosRam: "2", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "I7" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "8 GB", modulosRam: "2", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "1 GB", modulosRam: "1", capacidadDisco: "200 GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "4 GB", modulosRam: "2", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "2 GB", modulosRam: "1", capacidadDisco: "160 GB", tipoDisco: "HDD", procesador: "DUAL CORE" },
    { memoriaRam: "2 GB", modulosRam: "1", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM 4" },
    { memoriaRam: "16 GB", modulosRam: "1", capacidadDisco: "512 GB", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "CORE i7" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "2 GB", modulosRam: "1", capacidadDisco: "260 GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "8 GB", modulosRam: "2", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "CORE i7" },
    { memoriaRam: "1 GB", modulosRam: "1", capacidadDisco: "160 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2 GB", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2 GB", modulosRam: "1", capacidadDisco: "160 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "I5" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "120 GB", tipoDisco: "SSD", procesador: "I7" },
    { memoriaRam: "2 GB", modulosRam: "1", capacidadDisco: "230 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "I3" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "120 GB", tipoDisco: "SSD", procesador: "CORE i5" },
    { memoriaRam: "16 GB", modulosRam: "1", capacidadDisco: "512 GB", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "2 GB", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 GB", modulosRam: "2", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "1 GB", modulosRam: "1", capacidadDisco: "160 GB", tipoDisco: "HDD", procesador: "DUAL CORE" },
    { memoriaRam: "1.5 GB", modulosRam: "2", capacidadDisco: "160 GB", tipoDisco: "HDD", procesador: "DUAL CORE" },
    { memoriaRam: "8 GB", modulosRam: "2", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "I7" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "3 GB", modulosRam: "2", capacidadDisco: "250 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "8 GB", modulosRam: "2", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "2 GB", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "N/A", modulosRam: "N/A", capacidadDisco: "N/A", tipoDisco: "N/A", procesador: "N/A" },
    { memoriaRam: "512 MB", modulosRam: "2", capacidadDisco: "40 GB", tipoDisco: "HDD", procesador: "PENTIUM 4" },
    { memoriaRam: "1 GB", modulosRam: "2", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "3 GB", modulosRam: "3", capacidadDisco: "160 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "i3" },
    { memoriaRam: "384 MB", modulosRam: "3", capacidadDisco: "30 GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "1 GB", modulosRam: "1", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "DUAL CORE" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "1 DDR2 533MHZ", modulosRam: "2", capacidadDisco: "80 (6) GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "2 DDR3 1333 MHZ", modulosRam: "1", capacidadDisco: "80 (57MB) GB", tipoDisco: "HDD", procesador: "DUAL CORE" },
    { memoriaRam: "2 DDR2 667 MHZ", modulosRam: "2", capacidadDisco: "160 (5.47) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2 DDR3 1333 MHZ", modulosRam: "1", capacidadDisco: "500 (16.5) GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "2 DDR3 1333 MHZ", modulosRam: "1", capacidadDisco: "NO POSEE", tipoDisco: "N/A", procesador: "PENTIUM" },
    { memoriaRam: "DESCONOCIDO", modulosRam: "DESCONOCIDO", capacidadDisco: "NO POSEE", tipoDisco: "N/A", procesador: "NO POSEE" },
    { memoriaRam: "16 GB", modulosRam: "1", capacidadDisco: "512 GB", tipoDisco: "M2", procesador: "I5" },
    { memoriaRam: "4 GB", modulosRam: "2", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 GB", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "16 GB", modulosRam: "1", capacidadDisco: "512 GB", tipoDisco: "M2", procesador: "I5" },
    { memoriaRam: "8 DDR3 (1333)", modulosRam: "2", capacidadDisco: "320 (2) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3 1333", modulosRam: "1", capacidadDisco: "320 (3) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "2 DDR2 (400)", modulosRam: "1", capacidadDisco: "160 (5) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 DDR3 1333", modulosRam: "1", capacidadDisco: "500 (22) GB", tipoDisco: "HDD", procesador: "I5" },
    { memoriaRam: "2 DDR3 1333", modulosRam: "1", capacidadDisco: "320 (44) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "8 DDR3 (1600)", modulosRam: "2", capacidadDisco: "1000 (54) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "8 DDR3 (1600)", modulosRam: "2", capacidadDisco: "1000 (61) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "8 DDR3 (1600)", modulosRam: "2", capacidadDisco: "1000 (39) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "2 DDR3 1333", modulosRam: "1", capacidadDisco: "320 (18) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "8 DDR3 (1600)", modulosRam: "2", capacidadDisco: "1000 (2) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "8 DDR3 (1600)", modulosRam: "2", capacidadDisco: "1000 GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "500 MB", modulosRam: "2", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "16 DDR4 (3200)", modulosRam: "2", capacidadDisco: "512 (5) GB", tipoDisco: "SSD", procesador: "i5" },
    { memoriaRam: "16 DDR4 (1600)", modulosRam: "1", capacidadDisco: "512 (17) GB", tipoDisco: "M2", procesador: "i5" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "1", capacidadDisco: "1000 (13) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "1", capacidadDisco: "1000 (17) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "1", capacidadDisco: "1000 (5) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (68) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "1", capacidadDisco: "1000 (20) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "2 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2 DDR2 (6400)", modulosRam: "1", capacidadDisco: "180 (7) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2 DDR2 (6400)", modulosRam: "1", capacidadDisco: "180 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (26) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "1", capacidadDisco: "1000 (91) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "1", capacidadDisco: "1000 (52) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "1", capacidadDisco: "1000 (72) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "1", capacidadDisco: "1000 (93) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "500 MB PC2", modulosRam: "1", capacidadDisco: "160 GB", tipoDisco: "HDD", procesador: "N/A" },
    { memoriaRam: "2 PC2 (6400)", modulosRam: "1", capacidadDisco: "180 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2 DDR3 (10700)", modulosRam: "1", capacidadDisco: "320 (31) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 DDR3 (10600)", modulosRam: "1", capacidadDisco: "320 (12) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (35) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "8 PC3 (12800)", modulosRam: "2", capacidadDisco: "1000 (9992) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (13) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "1.5 PC2 (5300)", modulosRam: "2", capacidadDisco: "160 (37) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (10) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (23) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "1.5 PC2 (5300)", modulosRam: "2", capacidadDisco: "160 (9) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (18) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3 (10600)", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "4 DDR3 (10600)", modulosRam: "1", capacidadDisco: "320 (75) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "1 DDR2 (6400)", modulosRam: "2", capacidadDisco: "80 (20) GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "2 PC2 5300", modulosRam: "1", capacidadDisco: "320 (75) GB", tipoDisco: "HDD", procesador: "CORE DUO" },
    { memoriaRam: "N/A", modulosRam: "N/A", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "500 (4.5) GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (13.1) GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "1 DDR2 667MHZ", modulosRam: "2", capacidadDisco: "80 (1) GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "4", modulosRam: "1", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "1 DDR2 667MHZ", modulosRam: "1", capacidadDisco: "80 (1) GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "32 DDR4 3200", modulosRam: "2", capacidadDisco: "1000 (7) GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "2 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "160 (2) GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (1) GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (5) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (6) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (4) GB", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (18) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "2 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (15) GB", tipoDisco: "HDD", procesador: "CORE DUO" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (19) GB", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (27) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (5) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (16) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "1", modulosRam: "2", capacidadDisco: "80 (4) GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "8 DDR3 1600MHZ", modulosRam: "2", capacidadDisco: "1000 (41) GB", tipoDisco: "HDD", procesador: "CORE i7" },
    { memoriaRam: "8 DDR3 1600MHZ", modulosRam: "2", capacidadDisco: "1000 (250) GB", tipoDisco: "HDD", procesador: "CORE i7" },
    { memoriaRam: "16 DDR4 3200MHZ", modulosRam: "1", capacidadDisco: "512 (107) GB", tipoDisco: "M2", procesador: "CORE i5" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "500 (11) GB", tipoDisco: "HDD", procesador: "I5" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "1", capacidadDisco: "320 (5) GB", tipoDisco: "HDD", procesador: "I7" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "500 (7) GB", tipoDisco: "HDD", procesador: "I5" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (12) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "2 DDR2 (6300)", modulosRam: "1", capacidadDisco: "160 (1) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "1 DDR2 (6300)", modulosRam: "1", capacidadDisco: "160 (2) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "1", capacidadDisco: "1000 (250) GB", tipoDisco: "HDD", procesador: "I7" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "120 (14) / 320 GB", tipoDisco: "SSD/HDD", procesador: "AMD" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (21) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "2", capacidadDisco: "1000 (67) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 (12800)", modulosRam: "1", capacidadDisco: "120 (4) / 80 (74) GB", tipoDisco: "SSD/HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (26) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 PC3 (128000)", modulosRam: "1", capacidadDisco: "80 (14) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "2", modulosRam: "1", capacidadDisco: "500 (500MB) GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "4 DDR4 (2133)", modulosRam: "1", capacidadDisco: "500 (4) GB", tipoDisco: "HDD", procesador: "CELERON" },
    { memoriaRam: "16 DDR4 (3200)", modulosRam: "2", capacidadDisco: "226 (21) / 1000 (0) GB", tipoDisco: "SSD / HDD", procesador: "i7" },
    { memoriaRam: "16 DDR4 (3200)", modulosRam: "1", capacidadDisco: "5012 (24) GB", tipoDisco: "M2", procesador: "i5" },
    { memoriaRam: "16 DDR4 (3200)", modulosRam: "1", capacidadDisco: "512 (10) GB", tipoDisco: "SSD", procesador: "i5" },
    { memoriaRam: "8 PC3 (12800)", modulosRam: "2", capacidadDisco: "500 (20) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "16 DDR4 (2666)", modulosRam: "2", capacidadDisco: "512 (5) / 2000 (162MB) GB", tipoDisco: "HDD / SSD", procesador: "i7" },
    { memoriaRam: "N/A", modulosRam: "N/A", capacidadDisco: "N/A", tipoDisco: "N/A", procesador: "N/A" },
    { memoriaRam: "1 PC2", modulosRam: "2", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM" },
    { memoriaRam: "2", modulosRam: "1", capacidadDisco: "320 (3) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 PC3 (107000)", modulosRam: "1", capacidadDisco: "320 (7) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "2 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (9) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 PC3 (107000)", modulosRam: "1", capacidadDisco: "320 (3) GB", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "4 PC3 (10700)", modulosRam: "1", capacidadDisco: "320 (18) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "2 PC3 (10700)", modulosRam: "1", capacidadDisco: "160 (1) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (3) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "8 DDR3 1333MHZ", modulosRam: "2", capacidadDisco: "500 (7) GB", tipoDisco: "HDD", procesador: "CORE i7" },
    { memoriaRam: "2 GB", modulosRam: "1", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (30) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "4 PC3 10700", modulosRam: "1", capacidadDisco: "320 (6) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "NO POSEE", modulosRam: "N/A", capacidadDisco: "NO POSEE", tipoDisco: "N/A", procesador: "AMD" },
    { memoriaRam: "2 DDR2", modulosRam: "1", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "4 PC3 10700", modulosRam: "1", capacidadDisco: "320 (16) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 PC2", modulosRam: "2", capacidadDisco: "160 GB", tipoDisco: "HDD", procesador: "PENTIUM 4" },
    { memoriaRam: "4 PC2", modulosRam: "2", capacidadDisco: "500 GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 DDR3 10700", modulosRam: "2", capacidadDisco: "160 GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "4 DDR3 10700", modulosRam: "1", capacidadDisco: "80 GB", tipoDisco: "HDD", procesador: "i3" },
    { memoriaRam: "4 PC3 10700", modulosRam: "1", capacidadDisco: "320 (8) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "NO POSEE", modulosRam: "NO POSEE", capacidadDisco: "NO POSEE", tipoDisco: "NO POSEE", procesador: "i5" },
    { memoriaRam: "1 DDR2", modulosRam: "1", capacidadDisco: "80 (7) GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "4 PC3 10700", modulosRam: "1", capacidadDisco: "500 (4) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "2 PC3 10700", modulosRam: "1", capacidadDisco: "320 (1) GB", tipoDisco: "HDD", procesador: "CORE 2 DUO" },
    { memoriaRam: "4 PC3 10700", modulosRam: "1", capacidadDisco: "320 (13) GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "4 PC3 10700", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "AMD" },
    { memoriaRam: "8 PC3 12800", modulosRam: "1", capacidadDisco: "500 (7) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "16 DDR4 3200", modulosRam: "1", capacidadDisco: "500 (15) GB", tipoDisco: "M2", procesador: "I5 1135" },
    { memoriaRam: "16 DDR4 3200", modulosRam: "1", capacidadDisco: "500 (4) GB", tipoDisco: "M2", procesador: "I5 1135" },
    { memoriaRam: "4 PC3 10700", modulosRam: "1", capacidadDisco: "500 (3) GB", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "8 PC3 12800", modulosRam: "2", capacidadDisco: "500 (44) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "8 PC3 12800", modulosRam: "2", capacidadDisco: "1000 (492) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "1 PC2 5300", modulosRam: "2", capacidadDisco: "80 (1.5) GB", tipoDisco: "HDD", procesador: "PENTIUM D" },
    { memoriaRam: "4 PC3 10700", modulosRam: "1", capacidadDisco: "80 (7) GB", tipoDisco: "HDD", procesador: "i5" },
    { memoriaRam: "8 PC3 12800", modulosRam: "2", capacidadDisco: "1000 (17) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "8 PC3 12800", modulosRam: "2", capacidadDisco: "1000 (15) GB", tipoDisco: "HDD", procesador: "i7" },
    { memoriaRam: "4 PC3 10700", modulosRam: "1", capacidadDisco: "N/A", tipoDisco: "HDD", procesador: "CORE I5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (11) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "500 (8) GB", tipoDisco: "HDD", procesador: "CORE i5" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "120 (60) GB", tipoDisco: "SSD", procesador: "AMD X2" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (10) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 (29) GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "4 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "320 GB", tipoDisco: "HDD", procesador: "AMD X2" },
    { memoriaRam: "2 DDR3 1333MHZ", modulosRam: "1", capacidadDisco: "NO POSEE", tipoDisco: "N/A", procesador: "CORE 2 DUO" },
    { memoriaRam: "NO POSEE", modulosRam: "N/A", capacidadDisco: "NO POSEE", tipoDisco: "N/A", procesador: "CORE I5" }
    ], skipDuplicates: true,
    });
    
    console.log("Especificaciones adicionales creadas.");
}